lenovobios_secondflash: Warn if BUCTS is not present.

diff --git a/lenovobios_secondflash b/lenovobios_secondflash
--- a/lenovobios_secondflash
+++ b/lenovobios_secondflash
@@ -42,5 +42,10 @@ fi
 ./flashrom/flashrom -p internal -w $1
 
 # Advised. Reset back to 0.
-./bucts/bucts 0
-
+{ # try
+	./bucts/bucts 0
+} || { # catch
+	echo "WARNING: bucts not found, but if the image was flashed then it's probably safe."
+	echo "A dd'd image (like libreboot's images) flashed with bucts=1 is ok. If the image is not dd'd and bucts=1,"
+	echo "then you should run ./bucts 0 now, or remove the yellow cmos/nvram battery for a minute."
+}
