Conditionally bootstrap CrossGCC build
It's possible that a compilation failure will occur if there's a
difference in major versions between the host GCC compiler and the one
being built.  To avoid this, bootstrapping can be used.  The method
for bootstrapping is simply passing the '-b' flag to Make; the
Makefile takes care of the rest.

diff --git a/projects/crossgcc/crossgcc b/projects/crossgcc/crossgcc
--- a/projects/crossgcc/crossgcc
+++ b/projects/crossgcc/crossgcc
@@ -145,7 +145,16 @@ build() {
 
 	mkdir -p "$build_path"
 
-	make -C "$sources_path" CPUS="$TASKS" DEST="$build_path" "crossgcc-$arch"
+	local bootstrap_flag
+
+	if ! crossgcc_same_major_version_test; then
+		printf '\n%s' 'GCC major versions differ.  Bootstrapping' 1>&2
+		printf '%s\n\n' ' to avoid potential build failure' 1>&2
+
+		bootstrap_flag='-b'
+	fi
+
+	make -C "$sources_path" "$bootstrap_flag" CPUS="$TASKS" DEST="$build_path" "crossgcc-$arch"
 }
 
 build_check() {
