Remove unnecessary 'env' invocation from printf.
This reverts part of pull request #217 which called the 'env'
binary for each printf invocation.

diff --git a/libs/common b/libs/common
--- a/libs/common
+++ b/libs/common
@@ -60,7 +60,7 @@ arguments_list() {
 
 	for argument in "$@"
 	do
-		env printf '%s\n' "$argument"
+		printf '%s\n' "$argument"
 	done
 }
 
@@ -85,7 +85,7 @@ path_wildcard_expand() {
 	local path=$@
 
 	# Evaluation fails with unescaped whitespaces.
-	path=$( env printf '%s\n' "$path" | sed "s/ /\\\ /g" )
+	path=$( printf '%s\n' "$path" | sed "s/ /\\\ /g" )
 
 	eval "arguments_list "$path""
 }
@@ -112,7 +112,7 @@ file_checksum_check() {
 
 	if ! [ -f "$checksum_path" ]
 	then
-		env printf '%s\n' 'Could not verify file checksum!' >&2
+		printf '%s\n' 'Could not verify file checksum!' >&2
 		return 1
 	fi
 
@@ -142,7 +142,7 @@ file_signature_check() {
 
 	if ! [ -f "$signature_path" ]
 	then
-		env printf '%s\n' 'Could not verify file signature!' >&2
+		printf '%s\n' 'Could not verify file signature!' >&2
 		return 1
 	fi
 
@@ -336,7 +336,7 @@ requirements() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
@@ -353,7 +353,7 @@ requirements_root() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
@@ -375,22 +375,22 @@ arguments_concat() {
 		fi
 	done
 
-	env printf '%s\n' "$concat"
+	printf '%s\n' "$concat"
 }
 
 execute_root() {
 	local sudo=$( which sudo 2> /dev/null || true )
 	local arguments
 
-	env printf '%s' 'Running command as root: ' >&2
-	env printf '%b\n' "$*" >&2
+	printf '%s' 'Running command as root: ' >&2
+	printf '%b\n' "$*" >&2
 
 	if ! [ -z "$sudo" ]
 	then
 		sudo "$@"
 	else
 		# Quote arguments for eval through su.
-		arguments=$( env printf '%q ' "$@" )
+		arguments=$( printf '%q ' "$@" )
 		su -c "$arguments"
 	fi
 }
diff --git a/projects/cros-scripts/install/cros-boot-keys b/projects/cros-scripts/install/cros-boot-keys
--- a/projects/cros-scripts/install/cros-boot-keys
+++ b/projects/cros-scripts/install/cros-boot-keys
@@ -31,16 +31,16 @@ ALGORITHMS="7 7 11 7 7 4 11 11 11"
 MODES="7 7 11 7 10"
 
 usage() {
-	env printf '%s\n' "$executable [action]" >&2
+	printf '%s\n' "$executable [action]" >&2
 
-	env printf '\n%s\n' 'Actions:' >&2
-	env printf '%s\n' '  generate - Generate a set of keys' >&2
-	env printf '%s\n' '  verify - Verify keyblocks' >&2
+	printf '\n%s\n' 'Actions:' >&2
+	printf '%s\n' '  generate - Generate a set of keys' >&2
+	printf '%s\n' '  verify - Verify keyblocks' >&2
 
-	env printf '\n%s\n' 'Environment variables:' >&2
-	env printf '%s\n' '  KEYS_VERSION - Version to give the keys' >&2
-	env printf '%s\n' '  VBOOT_KEYS_PATH - Path to the vboot keys' >&2
-	env printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
+	printf '\n%s\n' 'Environment variables:' >&2
+	printf '%s\n' '  KEYS_VERSION - Version to give the keys' >&2
+	printf '%s\n' '  VBOOT_KEYS_PATH - Path to the vboot keys' >&2
+	printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
 }
 
 keys_override_confirm() {
@@ -68,9 +68,9 @@ keys_override_confirm() {
 		return 0
 	fi
 
-	env printf '%s\n' 'This is going to override keys stored in the following directory:'
-	env printf '%s\n' "  $VBOOT_KEYS_PATH"
-	env printf '%s' 'Press enter to confirm: '
+	printf '%s\n' 'This is going to override keys stored in the following directory:'
+	printf '%s\n' "  $VBOOT_KEYS_PATH"
+	printf '%s' 'Press enter to confirm: '
 
 	read confirm
 }
@@ -89,8 +89,8 @@ generate() {
 
 	for key in $KEYS
 	do
-		algorithm=$( env printf '%s\n' "$algorithms" | sed "s/$REGEXP/\1/g" )
-		algorithms=$( env printf '%s\n' "$algorithms" | sed "s/$REGEXP/\2/g" )
+		algorithm=$( printf '%s\n' "$algorithms" | sed "s/$REGEXP/\1/g" )
+		algorithms=$( printf '%s\n' "$algorithms" | sed "s/$REGEXP/\2/g" )
 
 		key_length=$(( 1 << (10 + ($algorithm / 3)) ))
 
@@ -104,23 +104,23 @@ generate() {
 		rm -f "$VBOOT_KEYS_PATH/$key.$PEM" "$VBOOT_KEYS_PATH/$key.$CRT" "$VBOOT_KEYS_PATH/$key.$KEYB"
 	done
 
-	env printf '\n%s\n' "Generated keys $KEYS"
+	printf '\n%s\n' "Generated keys $KEYS"
 
 	for keyblock in $KEYBLOCKS
 	do
-		pubkey=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
-		subkeys=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
-		privkey=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
-		subkeys=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
+		pubkey=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
+		subkeys=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
+		privkey=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
+		subkeys=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
 
-		mode=$( env printf '%s\n' "$modes" | sed "s/$REGEXP/\1/g" )
-		modes=$( env printf '%s\n' "$modes" | sed "s/$REGEXP/\2/g" )
+		mode=$( printf '%s\n' "$modes" | sed "s/$REGEXP/\1/g" )
+		modes=$( printf '%s\n' "$modes" | sed "s/$REGEXP/\2/g" )
 
 		futility vbutil_keyblock --pack "$VBOOT_KEYS_PATH/$keyblock.$KEYBLOCK" --flags "$mode" --datapubkey "$VBOOT_KEYS_PATH/$pubkey.$VBPUBK" --signprivate "$VBOOT_KEYS_PATH/$privkey.$VBPRIVK"
 		futility vbutil_keyblock --unpack "$VBOOT_KEYS_PATH/$keyblock.$KEYBLOCK" --signpubkey "$VBOOT_KEYS_PATH/$privkey.$VBPUBK"
 	done
 
-	env printf '\n%s\n' "Generated keyblocks $KEYBLOCKS"
+	printf '\n%s\n' "Generated keyblocks $KEYBLOCKS"
 }
 
 verify() {
@@ -130,15 +130,15 @@ verify() {
 
 	for keyblock in $KEYBLOCKS
 	do
-		pubkey=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
-		subkeys=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
-		privkey=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
-		subkeys=$( env printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
+		pubkey=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
+		subkeys=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
+		privkey=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\1/g" )
+		subkeys=$( printf '%s\n' "$subkeys" | sed "s/$REGEXP/\2/g" )
 
 		futility vbutil_keyblock --unpack "$VBOOT_KEYS_PATH/$keyblock.$KEYBLOCK" --signpubkey "$VBOOT_KEYS_PATH/$privkey.$VBPUBK"
 	done
 
-	env printf '\n%s\n' "Verified keyblocks $KEYBLOCKS"
+	printf '\n%s\n' "Verified keyblocks $KEYBLOCKS"
 }
 
 requirements() {
@@ -151,7 +151,7 @@ requirements() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
diff --git a/projects/cros-scripts/install/cros-kernel-install b/projects/cros-scripts/install/cros-kernel-install
--- a/projects/cros-scripts/install/cros-kernel-install
+++ b/projects/cros-scripts/install/cros-kernel-install
@@ -23,22 +23,22 @@ MODEL="model"
 NAME="name"
 
 usage() {
-	env printf '%s\n' "$executable [action] [storage] [kernel image|kernel modules]" >&2
+	printf '%s\n' "$executable [action] [storage] [kernel image|kernel modules]" >&2
 
-	env printf '\n%s\n' 'Actions:' >&2
-	env printf '%s\n' '  backup - Backup kernel image' >&2
-	env printf '%s\n' '  image - Install kernel image' >&2
-	env printf '%s\n' '  modules - Install kernel modules' >&2
+	printf '\n%s\n' 'Actions:' >&2
+	printf '%s\n' '  backup - Backup kernel image' >&2
+	printf '%s\n' '  image - Install kernel image' >&2
+	printf '%s\n' '  modules - Install kernel modules' >&2
 
 	usage_storage
 
-	env printf '\n%s\n' 'Environment variables:' >&2
-	env printf '%s\n' '  VBOOT_KEYS_PATH - Path to the vboot keys' >&2
-	env printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
+	printf '\n%s\n' 'Environment variables:' >&2
+	printf '%s\n' '  VBOOT_KEYS_PATH - Path to the vboot keys' >&2
+	printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
 }
 
 usage_storage() {
-	env printf '\n%s\n' 'Storage:' >&2
+	printf '\n%s\n' 'Storage:' >&2
 
 	local nodes=$( ls "$SYS_BLOCK_PATH" )
 	local node_path
@@ -58,7 +58,7 @@ usage_storage() {
 			continue
 		fi
 
-		env printf '%s\n' "  $node_path - $name" >&2
+		printf '%s\n' "  $node_path - $name" >&2
 	done
 }
 
@@ -68,9 +68,9 @@ storage_affect_confirm() {
 	local name=$( storage_name "$storage_path" )
 	local confirm
 
-	env printf '%s\n' 'This is going to affect the following storage:'
-	env printf '%s\n' "  $storage_path - $name"
-	env printf '%s' 'Press enter to confirm: '
+	printf '%s\n' 'This is going to affect the following storage:'
+	printf '%s\n' "  $storage_path - $name"
+	printf '%s' 'Press enter to confirm: '
 
 	read confirm
 }
@@ -95,17 +95,17 @@ storage_name() {
 		return 0
 	fi
 
-	name=$( env printf '%s\n' "$name" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
+	name=$( printf '%s\n' "$name" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
 
 	if [ -f "$vendor_path" ]
 	then
 		vendor=$( cat "$vendor_path" )
-		vendor=$( env printf '%s\n' "$vendor" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
+		vendor=$( printf '%s\n' "$vendor" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
 
 		name="$vendor $name"
 	fi
 
-	env printf '%s\n' "$name"
+	printf '%s\n' "$name"
 }
 
 storage_partition_path() {
@@ -124,7 +124,7 @@ storage_partition_path() {
 		return 1
 	fi
 
-	env printf '%s\n' "$storage_partition_path"
+	printf '%s\n' "$storage_partition_path"
 }
 
 storage_partition_mount_path() {
@@ -132,7 +132,7 @@ storage_partition_mount_path() {
 
 	local storage_partition_mount_path=$( udisksctl info -b "$storage_partition_path"  | grep "MountPoints" | sed "s/.*MountPoints:[[:space:]]*\(.*\)/\1/g" )
 
-	env printf '%s\n' "$storage_partition_mount_path"
+	printf '%s\n' "$storage_partition_mount_path"
 }
 
 storage_kernel_path() {
@@ -155,13 +155,13 @@ backup() {
 
 	if [ -z "$storage_kernel_path" ]
 	then
-		env printf '%s\n' "No kernel partition found on storage $storage_path" >&2
+		printf '%s\n' "No kernel partition found on storage $storage_path" >&2
 		return 1
 	fi
 
 	cat "$storage_kernel_path" > "$kernel_image_path"
 
-	env printf '\n%s\n' "Backed up kernel image to $kernel_image_path"
+	printf '\n%s\n' "Backed up kernel image to $kernel_image_path"
 }
 
 image() {
@@ -172,7 +172,7 @@ image() {
 
 	if [ -z "$storage_kernel_path" ]
 	then
-		env printf '%s\n' "No kernel partition found on storage $storage_path" >&2
+		printf '%s\n' "No kernel partition found on storage $storage_path" >&2
 		return 1
 	fi
 
@@ -181,7 +181,7 @@ image() {
 	cat "$kernel_image_path" > "$storage_kernel_path"
 	sync
 
-	env printf '\n%s\n' "Installed kernel image on storage $storage_path"
+	printf '\n%s\n' "Installed kernel image on storage $storage_path"
 }
 
 modules() {
@@ -192,7 +192,7 @@ modules() {
 
 	if [ -z "$storage_rootfs_path" ]
 	then
-		env printf '%s\n' "No rootfs partition found on storage $storage_path" >&2
+		printf '%s\n' "No rootfs partition found on storage $storage_path" >&2
 		return 1
 	fi
 
@@ -208,7 +208,7 @@ modules() {
 
 	udisksctl unmount -b "$storage_rootfs_path"
 
-	env printf '\n%s\n' "Installed kernel modules on storage $storage_path"
+	printf '\n%s\n' "Installed kernel modules on storage $storage_path"
 }
 
 requirements() {
@@ -221,7 +221,7 @@ requirements() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
diff --git a/projects/cros-scripts/install/cros-kernel-prepare b/projects/cros-scripts/install/cros-kernel-prepare
--- a/projects/cros-scripts/install/cros-kernel-prepare
+++ b/projects/cros-scripts/install/cros-kernel-prepare
@@ -27,21 +27,21 @@ FIT="fit"
 IMG="img"
 
 usage() {
-	env printf '%s\n' "$executable [action] [kernel files|kernel image] [medium]" >&2
+	printf '%s\n' "$executable [action] [kernel files|kernel image] [medium]" >&2
 
-	env printf '\n%s\n' 'Actions:' >&2
-	env printf '%s\n' '  pack - Pack kernel files to a medium-specific image' >&2
-	env printf '%s\n' '  sign - Sign kernel image' >&2
-	env printf '%s\n' '  verify - Very kernel image signatures' >&2
+	printf '\n%s\n' 'Actions:' >&2
+	printf '%s\n' '  pack - Pack kernel files to a medium-specific image' >&2
+	printf '%s\n' '  sign - Sign kernel image' >&2
+	printf '%s\n' '  verify - Very kernel image signatures' >&2
 
-	env printf '\n%s\n' 'Medium:' >&2
-	env printf '%s\n' '  usb - External USB storage' >&2
-	env printf '%s\n' '  mmc - External SD card storage' >&2
-	env printf '%s\n' '  emmc - Internal storage' >&2
+	printf '\n%s\n' 'Medium:' >&2
+	printf '%s\n' '  usb - External USB storage' >&2
+	printf '%s\n' '  mmc - External SD card storage' >&2
+	printf '%s\n' '  emmc - Internal storage' >&2
 
-	env printf '\n%s\n' 'Environment variables:' >&2
-	env printf '%s\n' '  VBOOT_KEYS_PATH - Path to the vboot keys' >&2
-	env printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
+	printf '\n%s\n' 'Environment variables:' >&2
+	printf '%s\n' '  VBOOT_KEYS_PATH - Path to the vboot keys' >&2
+	printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
 }
 
 pack() {
@@ -59,7 +59,7 @@ pack() {
 	mkimage -f "$kernel_its_path" "$kernel_fit_path"
 	futility vbutil_kernel --pack "$kernel_image_path" --version 1 --arch "$arch" --keyblock "$VBOOT_KEYS_PATH/kernel.$KEYBLOCK" --signprivate "$VBOOT_KEYS_PATH/kernel_data_key.$VBPRIVK" --config "$cmdline_path" --vmlinuz "$kernel_fit_path" --bootloader "$bootloader_path"
 
-	env printf '\n%s\n' "Packed kernel image $kernel_image_path"
+	printf '\n%s\n' "Packed kernel image $kernel_image_path"
 }
 
 sign() {
@@ -67,7 +67,7 @@ sign() {
 
 	futility vbutil_kernel --repack "$kernel_image_path" --version 1 --keyblock "$VBOOT_KEYS_PATH/kernel.$KEYBLOCK" --signprivate "$VBOOT_KEYS_PATH/kernel_data_key.$VBPRIVK" --oldblob "$kernel_image_path"
 
-	env printf '\n%s\n' "Signed kernel image $kernel_image_path"
+	printf '\n%s\n' "Signed kernel image $kernel_image_path"
 }
 
 verify() {
@@ -75,7 +75,7 @@ verify() {
 
 	futility vbutil_kernel --verify "$kernel_image_path" --signpubkey "$VBOOT_KEYS_PATH/kernel_subkey.$VBPUBK"
 
-	env printf '\n%s\n' "Verified kernel image $kernel_image_path"
+	printf '\n%s\n' "Verified kernel image $kernel_image_path"
 }
 
 requirements() {
@@ -88,7 +88,7 @@ requirements() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
diff --git a/projects/cros-scripts/install/cros-medium-setup b/projects/cros-scripts/install/cros-medium-setup
--- a/projects/cros-scripts/install/cros-medium-setup
+++ b/projects/cros-scripts/install/cros-medium-setup
@@ -32,22 +32,22 @@ GPT_SIZE=34
 KERNEL_SIZE=16384
 
 usage() {
-	env printf '%s\n' "$executable [action] [storage] [rootfs tarball|kernel files] [medium]" >&2
+	printf '%s\n' "$executable [action] [storage] [rootfs tarball|kernel files] [medium]" >&2
 
-	env printf '\n%s\n' 'Actions:' >&2
-	env printf '%s\n' '  partitions - Setup partitions on storage' >&2
-	env printf '%s\n' '  rootfs - Install rootfs tarball to storage' >&2
-	env printf '%s\n' '  kernel - Install kernel files to storage' >&2
+	printf '\n%s\n' 'Actions:' >&2
+	printf '%s\n' '  partitions - Setup partitions on storage' >&2
+	printf '%s\n' '  rootfs - Install rootfs tarball to storage' >&2
+	printf '%s\n' '  kernel - Install kernel files to storage' >&2
 
 	usage_storage
 
-	env printf '\n%s\n' 'Environment variables:' >&2
-	env printf '%s\n' '  KERNEL_PATH - Path to the kernel image' >&2
-	env printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
+	printf '\n%s\n' 'Environment variables:' >&2
+	printf '%s\n' '  KERNEL_PATH - Path to the kernel image' >&2
+	printf '%s\n' '  VBOOT_TOOLS_PATH - Path to vboot tools' >&2
 }
 
 usage_storage() {
-	env printf '\n%s\n' 'Storage:' >&2
+	printf '\n%s\n' 'Storage:' >&2
 
 	local nodes=$( ls "$SYS_BLOCK_PATH" )
 	local node_path
@@ -67,7 +67,7 @@ usage_storage() {
 			continue
 		fi
 
-		env printf '%s\n' "  $node_path - $name" >&2
+		printf '%s\n' "  $node_path - $name" >&2
 	done
 }
 
@@ -77,9 +77,9 @@ storage_affect_confirm() {
 	local name=$( storage_name "$storage_path" )
 	local confirm
 
-	env printf '%s\n' 'This is going to affect the following storage:'
-	env printf '%s\n' "  $storage_path - $name"
-	env printf '%s' 'Press enter to confirm: '
+	printf '%s\n' 'This is going to affect the following storage:'
+	printf '%s\n' "  $storage_path - $name"
+	printf '%s' 'Press enter to confirm: '
 
 	read confirm
 }
@@ -104,17 +104,17 @@ storage_name() {
 		return 0
 	fi
 
-	name=$( env printf '%s\n' "$name" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
+	name=$( printf '%s\n' "$name" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
 
 	if [ -f "$vendor_path" ]
 	then
 		vendor=$( cat "$vendor_path" )
-		vendor=$( env printf '%s\n' "$vendor" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
+		vendor=$( printf '%s\n' "$vendor" | sed -e "s/^[[:space:]]*//;s/[[:space:]]*$//" )
 
 		name="$vendor $name"
 	fi
 
-	env printf '%s\n' "$name"
+	printf '%s\n' "$name"
 }
 
 storage_partition_path() {
@@ -133,7 +133,7 @@ storage_partition_path() {
 		return 1
 	fi
 
-	env printf '%s\n' "$storage_partition_path"
+	printf '%s\n' "$storage_partition_path"
 }
 
 storage_partition_mount_path() {
@@ -141,7 +141,7 @@ storage_partition_mount_path() {
 
 	local storage_partition_mount_path=$( udisksctl info -b "$storage_partition_path"  | grep "MountPoints" | sed "s/.*MountPoints:[[:space:]]*\(.*\)/\1/g" )
 
-	env printf '%s\n' "$storage_partition_mount_path"
+	printf '%s\n' "$storage_partition_mount_path"
 }
 
 partitions() {
@@ -161,7 +161,7 @@ partitions() {
 		udisksctl unmount -b "$partition" || true
 	done
 
-	( env printf '%s\n' "g" ; env printf '%s\n' "w" ) | fdisk "$storage_path"
+	( printf '%s\n' "g" ; printf '%s\n' "w" ) | fdisk "$storage_path"
 
 	cgpt create "$storage_path"
 
@@ -180,7 +180,7 @@ partitions() {
 
 	mkfs.ext4 -F "$storage_rootfs_path"
 
-	env printf '\n%s\n' "Setup partitions on storage $storage_path"
+	printf '\n%s\n' "Setup partitions on storage $storage_path"
 }
 
 rootfs() {
@@ -201,7 +201,7 @@ rootfs() {
 
 	udisksctl unmount -b "$storage_rootfs_path"
 
-	env printf '\n%s\n' "Installed rootfs on storage $storage_path"
+	printf '\n%s\n' "Installed rootfs on storage $storage_path"
 }
 
 kernel() {
@@ -230,7 +230,7 @@ kernel() {
 
 	udisksctl unmount -b "$storage_rootfs_path"
 
-	env printf '\n%s\n' "Installed kernel on storage $storage_path"
+	printf '\n%s\n' "Installed kernel on storage $storage_path"
 }
 
 requirements() {
@@ -243,7 +243,7 @@ requirements() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
diff --git a/projects/libreboot-release/install/libreboot-release b/projects/libreboot-release/install/libreboot-release
--- a/projects/libreboot-release/install/libreboot-release
+++ b/projects/libreboot-release/install/libreboot-release
@@ -27,18 +27,18 @@ SHA256SUM="sha256sum"
 ASC="asc"
 
 usage() {
-	env printf '%s\n' "$executable [action] [projects...]" >&2
+	printf '%s\n' "$executable [action] [projects...]" >&2
 
-	env printf '\n%s\n' 'Actions:' >&2
-	env printf '%s\n' '  download - Download project files' >&2
-	env printf '%s\n' '  sources - Download project sources' >&2
-	env printf '%s\n' '  verify - Verify project files' >&2
-	env printf '%s\n' '  extract - Extract project files' >&2
-	env printf '%s\n' '  prepare - Download, verify and extract project files' >&2
+	printf '\n%s\n' 'Actions:' >&2
+	printf '%s\n' '  download - Download project files' >&2
+	printf '%s\n' '  sources - Download project sources' >&2
+	printf '%s\n' '  verify - Verify project files' >&2
+	printf '%s\n' '  extract - Extract project files' >&2
+	printf '%s\n' '  prepare - Download, verify and extract project files' >&2
 
-	env printf '\n%s\n' 'Environment variables:' >&2
-	env printf '%s\n' '  MACHINE - Machine architecture to use' >&2
-	env printf '%s\n' '  DOWNLOAD_URL - Base URL to download files from' >&2
+	printf '\n%s\n' 'Environment variables:' >&2
+	printf '%s\n' '  MACHINE - Machine architecture to use' >&2
+	printf '%s\n' '  DOWNLOAD_URL - Base URL to download files from' >&2
 }
 
 download() {
@@ -76,7 +76,7 @@ download() {
 				wget -O "$path.$SHA256SUM" "$url.$SHA256SUM"
 				wget -O "$path.$ASC" "$url.$ASC"
 
-				env printf '\n%s\n' "Downloaded $project"
+				printf '\n%s\n' "Downloaded $project"
 
 				return 0
 			fi
@@ -85,7 +85,7 @@ download() {
 		IFS=$ifs_save
 	done
 
-	env printf '%s\n' "Could not download $project from $DOWNLOAD_URL" >&2
+	printf '%s\n' "Could not download $project from $DOWNLOAD_URL" >&2
 	return 1
 }
 
@@ -102,9 +102,9 @@ sources() {
 		wget -O "$path.$SHA256SUM" "$url.$SHA256SUM"
 		wget -O "$path.$ASC" "$url.$ASC"
 
-		env printf '\n%s\n' "Downloaded $project sources"
+		printf '\n%s\n' "Downloaded $project sources"
 	else
-		env printf '%s\n' "Could not download $project sources from $DOWNLOAD_URL" >&2
+		printf '%s\n' "Could not download $project sources from $DOWNLOAD_URL" >&2
 		return 1
 	fi
 
@@ -153,17 +153,17 @@ verify() {
 					sha256sum -c "$project.$TAR_XZ.$SHA256SUM"
 				)
 			else
-				env printf '%s\n' "Could not verify $project checksum!" >&2
+				printf '%s\n' "Could not verify $project checksum!" >&2
 			fi
 
 			if [ -f "$signature_path" ]
 			then
 				gpg --armor --verify "$signature_path" "$path"
 			else
-				env printf '%s\n' "Could not verify $project signature!" >&2
+				printf '%s\n' "Could not verify $project signature!" >&2
 			fi
 
-			env printf '\n%s\n' "Verified $project"
+			printf '\n%s\n' "Verified $project"
 
 			return 0
 		done
@@ -171,7 +171,7 @@ verify() {
 		IFS=$ifs_save
 	done
 
-	env printf '%s\n' "Could not verify $project" >&2
+	printf '%s\n' "Could not verify $project" >&2
 	return 1
 }
 
@@ -209,7 +209,7 @@ extract() {
 
 			if [ "$prefix" = "$SYSTEMS/$MACHINE" ]
 			then
-				env printf '%s\n' "Skiping $project extract"
+				printf '%s\n' "Skiping $project extract"
 				return 0
 			fi
 
@@ -217,7 +217,7 @@ extract() {
 
 			tar -xf "$path" -ps -C "$extract_path"
 
-			env printf '%s\n' "Extracted $project"
+			printf '%s\n' "Extracted $project"
 
 			return 0
 		done
@@ -225,7 +225,7 @@ extract() {
 		IFS=$ifs_save
 	done
 
-	env printf '%s\n' "Could not extract $project" >&2
+	printf '%s\n' "Could not extract $project" >&2
 	return 1
 }
 
@@ -239,7 +239,7 @@ requirements() {
 
 		if [ -z "$requirement_path" ]
 		then
-			env printf '%s\n' "Missing requirement: $requirement" >&2
+			printf '%s\n' "Missing requirement: $requirement" >&2
 			exit 1
 		fi
 	done
@@ -256,7 +256,7 @@ setup() {
 
 	if [ -z "$DOWNLOAD_URL" ]
 	then
-		env printf '%s\n' 'Missing download URL' >&2
+		printf '%s\n' 'Missing download URL' >&2
 		exit 1
 	fi
 }
diff --git a/tools/boot-keys/boot-keys b/tools/boot-keys/boot-keys
--- a/tools/boot-keys/boot-keys
+++ b/tools/boot-keys/boot-keys
@@ -24,7 +24,7 @@ generate() {
 
 	if [ -z "$type" ]
 	then
-		env printf '%s\n' 'Unable to determine keys type' >&2
+		printf '%s\n' 'Unable to determine keys type' >&2
 		return 1
 	fi
 
@@ -47,11 +47,11 @@ sign() {
 
 	if [ -z "$type" ]
 	then
-		env printf '%s\n' 'Unable to determine keys type' >&2
+		printf '%s\n' 'Unable to determine keys type' >&2
 		return 1
 	fi
 
-	env printf '%s\n' "$prepare_files" | while read install_path
+	printf '%s\n' "$prepare_files" | while read install_path
 	do
 		case $type in
 			"cros-firmware")
@@ -90,11 +90,11 @@ verify() {
 
 	if [ -z "$type" ]
 	then
-		env printf '%s\n' 'Unable to determine keys type' >&2
+		printf '%s\n' 'Unable to determine keys type' >&2
 		return 1
 	fi
 
-	env printf '%s\n' "$prepare_files" | while read install_path
+	printf '%s\n' "$prepare_files" | while read install_path
 	do
 		case $type in
 			"cros-firmware")
